name: File Example

on: [push]

jobs:
  file_job:
    runs-on: ubuntu-latest
    env:
      FILE: keko.txt
    steps:
     - name: Set the value
       id: step_one
       run: |
        echo "action_state=yellow" >> $GITHUB_ENV
     - name: Use the value
       id: step_two
       run: |
         echo "${{ env.action_state }}"
