name: Greeting on variable day

on: [push]

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Keko

  file_job:
    runs-on: ubuntu-latest
    env:
      FILE: hello.txt
    steps:
      - name: " Check file"
      - run: |
          if [ -f "${FILE}" ]; then
            echo "$FILE exists."
          else 
           echo "$FILE does not exist."
          fi;
